-- MySQL Script generated by MySQL Workbench
-- Thu Oct 29 16:49:24 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema testParser
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `testParser` ;

-- -----------------------------------------------------
-- Schema testParser
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `testParser` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `testParser` ;

-- -----------------------------------------------------
-- Table `testParser`.`clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testParser`.`clients` ;

CREATE TABLE IF NOT EXISTS `testParser`.`clients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reg_number` VARCHAR(40) NOT NULL DEFAULT '111',
  `company_name` VARCHAR(255) NOT NULL DEFAULT 'компания',
  `url` VARCHAR(255) NOT NULL DEFAULT 'www.example.com',
  `phone_number` VARCHAR(60) NOT NULL DEFAULT '911',
  `email` VARCHAR(150) NOT NULL DEFAULT 'some@mail',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testParser`.`log_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testParser`.`log_table` ;

CREATE TABLE IF NOT EXISTS `testParser`.`log_table` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `source` VARCHAR(45) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `log_event` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testParser`.`db_controller`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testParser`.`db_controller` ;

CREATE TABLE IF NOT EXISTS `testParser`.`db_controller` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `file_name` VARCHAR(100) NOT NULL DEFAULT 'some.file',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS parser_user;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'parser_user' IDENTIFIED BY 'password123';

GRANT ALL ON `testParser`.* TO 'parser_user';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
